[pytest]
filterwarnings =
    ignore:Python 3.7 is no longer supported by the Python core team.*:cryptography.utils.CryptographyDeprecationWarning
    ignore:Python 3.7 is no longer supported by the Python core team.*
    ignore:datetime\.datetime\.utcfromtimestamp\(\) is deprecated.*:DeprecationWarning
    ignore:There is no current event loop:DeprecationWarning
    ignore:websockets\.InvalidStatusCode is deprecated:DeprecationWarning
    ignore:websockets\.legacy is deprecated.*:DeprecationWarning
